"""Re-export path_helper cho module veo3 (tương thích import cũ)."""
from utils.path_helper import (  # noqa: F401
    BASE_DIR,
    BUNDLE_DIR,
    CONFIG_DIR,
    CONFIG_FILE,
    GENERATED_DIR,
    PROJECTS_DIR,
    STORAGE_DIR,
    TASKS_FILE,
    VEO_AUTH_FILE,
    ensure_runtime_dirs,
    get_base_path,
    get_bundle_dir,
    get_paths_diagnostic,
    init_frozen_flag,
    is_running_as_exe,
    migrate_legacy_paths,
    normalize_script_path,
    pstr,
    resolve_resource,
    setup_runtime_cwd,
)
